"""Data models for the SEO Pipeline."""

from seo_pipeline.models.analysis import (
    BriefingAio,
    BriefingAioReference,
    BriefingCompetitor,
    BriefingCompetitorAnalysis,
    BriefingContentAnalysis,
    BriefingData,
    BriefingDataSources,
    BriefingFaqData,
    BriefingFaqQuestion,
    BriefingHeading,
    BriefingKeywordClusterSummary,
    BriefingKeywordData,
    BriefingMeta,
    BriefingQualitative,
    BriefingRating,
    BriefingSerpData,
    BriefingSerpFeatures,
    BriefingStats,
    Claim,
    ClaimsMeta,
    ClaimsOutput,
    CompetitorPageStructure,
    ContentFormatSignals,
    ContentTopics,
    CrossCompetitorAnalysis,
    Entity,
    EntityCandidate,
    EntityCluster,
    EntityProminence,
    PageStructure,
    PageStructureSection,
    ProminenceCorrection,
    ProminenceDebug,
    ProofKeyword,
    SectionWeight,
    WdfIdfMeta,
    WdfIdfScore,
    WdfIdfTerm,
)
from seo_pipeline.models.common import (
    Heading,
    HtmlSignals,
    LinkCount,
    PipelineBaseModel,
)
from seo_pipeline.models.keywords import (
    FaqItem,
    FilteredKeywords,
    Keyword,
    KeywordCluster,
    ProcessedKeywords,
    RemovalSummary,
    StrategistData,
)
from seo_pipeline.models.page import ExtractedPage, ExtractedPageError
from seo_pipeline.models.serp import (
    AiOverview,
    AiOverviewReference,
    CommercialSignals,
    CompetitorsData,
    Discussion,
    FeaturedSnippet,
    KnowledgeGraph,
    LocalSignals,
    PaaQuestion,
    Rating,
    RelatedSearch,
    SerpCompetitor,
    SerpFeatures,
    SerpProcessed,
    TopStory,
    VideoResult,
)

__all__ = [
    # common
    "PipelineBaseModel",
    "Heading",
    "LinkCount",
    "HtmlSignals",
    # keywords
    "Keyword",
    "KeywordCluster",
    "ProcessedKeywords",
    "FaqItem",
    "RemovalSummary",
    "FilteredKeywords",
    "StrategistData",
    # page
    "ExtractedPage",
    "ExtractedPageError",
    # serp
    "AiOverviewReference",
    "AiOverview",
    "FeaturedSnippet",
    "PaaQuestion",
    "KnowledgeGraph",
    "CommercialSignals",
    "LocalSignals",
    "RelatedSearch",
    "Discussion",
    "VideoResult",
    "TopStory",
    "SerpFeatures",
    "Rating",
    "SerpCompetitor",
    "SerpProcessed",
    "CompetitorsData",
    # analysis - content topics
    "ProofKeyword",
    "EntityCandidate",
    "SectionWeight",
    "ContentFormatSignals",
    "ContentTopics",
    # analysis - page structure
    "PageStructureSection",
    "CompetitorPageStructure",
    "CrossCompetitorAnalysis",
    "PageStructure",
    # analysis - entity prominence
    "Entity",
    "EntityCluster",
    "ProminenceCorrection",
    "ProminenceDebug",
    "EntityProminence",
    # analysis - claims
    "Claim",
    "ClaimsMeta",
    "ClaimsOutput",
    # analysis - wdf*idf
    "WdfIdfTerm",
    "WdfIdfMeta",
    "WdfIdfScore",
    # analysis - briefing data
    "BriefingDataSources",
    "BriefingMeta",
    "BriefingStats",
    "BriefingKeywordClusterSummary",
    "BriefingKeywordData",
    "BriefingSerpFeatures",
    "BriefingAioReference",
    "BriefingAio",
    "BriefingHeading",
    "BriefingRating",
    "BriefingCompetitor",
    "BriefingSerpData",
    "BriefingContentAnalysis",
    "BriefingCompetitorAnalysis",
    "BriefingFaqQuestion",
    "BriefingFaqData",
    "BriefingQualitative",
    "BriefingData",
]
